"""One-command evidence harness: runs everything from a clean checkout.

Usage:  python evidence/run_all.py
Every headline number is generated by benchmarks, not hand-written.
Exits non-zero on any failure.
"""
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def run(cmd):
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    sys.stdout.write(r.stdout)
    sys.stderr.write(r.stderr)
    if r.returncode != 0:
        raise SystemExit(f"FAILED: {' '.join(cmd)}")
    return r


def main() -> int:
    run([sys.executable, "evidence/extract_corpus.py"])
    run([sys.executable, "evidence/compact_bench.py"])
    run([sys.executable, "evidence/compact_aggressive.py"])
    run([sys.executable, "evidence/classifier_eval.py"])
    run([sys.executable, "evidence/tokenizer_blocker.py"])
    run([sys.executable, "evidence/build_realistic.py"])
    run([sys.executable, "evidence/classifier_realistic_eval.py"])
    run([sys.executable, "-m", "unittest", "discover", "-s", "evidence/tests"])
    run([sys.executable, "evidence/make_charts.py"])

    c = json.loads((HERE / "compact_report.json").read_text(encoding="utf-8"))
    a = json.loads((HERE / "compact_aggressive_report.json").read_text(encoding="utf-8"))
    k = json.loads((HERE / "classifier_report.json").read_text(encoding="utf-8"))
    r = json.loads((HERE / "classifier_realistic_report.json").read_text(encoding="utf-8"))
    blk = json.loads((HERE / "tokenizer_blocker.json").read_text(encoding="utf-8"))
    base = k["systems"]["baseline_regex"]
    imp = k["systems"]["improved_overlap"]
    rv2 = [(n, s) for n, s in r["systems"].items() if n.startswith("improved")][0]

    print("\n========================================")
    print("OPENCODE EVIDENCE SUMMARY (machine-generated)")
    print("========================================")
    print("\nCOMPACT TOOLS")
    print(f"{c['n_tools']} real tools")
    print(f"{c['avg_reduction_pct']}% average byte reduction (mean of per-tool; {c['total_ratio_pct']}% ratio of totals)")
    print(f"{c['median_pct']}% median reduction")
    print(f"{c['semantic_accuracy_pct']}% normalized semantic preservation (evaluated corpus)")
    print(f"{c['n_compacted']}/{c['n_tools']} compacted")
    print(f"{c['n_bypassed']} safe fallback")
    print(f"Encode: {c['avg_encode_ms']} ms")
    print(f"Decode: {c['avg_decode_ms']} ms")
    print(f"Aggressive (optional): {a['avg_reduction_pct']}% avg, {a['semantic_preserved']}/{a['n']} preserved ({a['verdict']})")
    print(f"Tokenizer (o200k_base): {blk['status']} — {blk['standing_result']}")
    print("\nCLASSIFIER (templated, synthetic)")
    print(f"Dataset: {k['n_total']} (train {k['n_train']} / test {k['n_test']})")
    print(f"Baseline acc: {base['accuracy']} F1: {base['macro_f1']} route-acc: {base['route_accuracy']}")
    print(f"Improved acc: {imp['accuracy']} F1: {imp['macro_f1']} route-acc: {imp['route_accuracy']}")
    print(f"Fallback: {imp['fallback_rate']}")
    print("\nCLASSIFIER (realistic, %s)" % r.get("source", "synthetic"))
    print(f"Dataset: {r['n_total']} (train {r['n_train']} / test {r['n_test']})")
    print(f"Baseline acc: {r['systems']['baseline_regex']['accuracy']} F1: {r['systems']['baseline_regex']['macro_f1']} route-acc: {r['systems']['baseline_regex']['route_accuracy']}")
    print(f"{rv2[0]}: acc {rv2[1]['accuracy']} F1 {rv2[1]['macro_f1']} route-acc: {rv2[1]['route_accuracy']}")
    print(f"Fallback: {rv2[1]['fallback_rate']}")
    print(f"Cost reduction vs always-large: {r['routing_value']['improved_vs_always_large_cost_saving_pct']}% (est. units)")
    print(f"Quality: routing-accuracy proxy only (no LLM key)")
    print("\nTESTS")
    print("unittest discover evidence/tests (see above; must be all OK)")
    print("\nREPRODUCIBILITY")
    print("PASS")
    print("\n========================================")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
