/**
 * Navigation extension seam — base layer, no-op.
 *
 * First link in the `/nav-ext*.js` chain (see
 * `common/core/extension-chain.js` for why it is a chain and not a slot, and
 * `navigation.js` for the layer list). It registers nothing, so the chain skips
 * it and navigation.js renders the base nav.
 *
 * To extend navigation in a distribution, do not edit this file — supply your
 * own layer's file (`nav-ext-ee.js`, `nav-ext-mt.js`) from your own overlay and
 * register a hooks object via data-sources under that layer's name. The
 * enterprise overlay's `nav-ext-ee.js` is the worked example. The hooks:
 *
 *   context()                    → resolved once per page, passed to the hooks below
 *   items(base, ctx)             → return the rail + topbar item array
 *   moduleNav(module, base, ctx) → return that module's tree, or null
 *
 * `base` is what the layers BELOW you produced, not the untouched OSS nav — a
 * hook that ignores it silently deletes everything they contributed.
 */
